version: 2.1

defaults: &defaults
  working_directory: ~/tomwells.org
  docker:
    - image: cimg/node:15.11-browsers

jobs:
  build-and-deploy:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - platform-patches
      - run:
          # Need to install a tool called sysconfcpus to overwrite the number of
          # reported cpus - which purescript compiler uses (circleci reports 32, but
          # that is not true)
          name: Build and install sysconfcpus
          command: 
            >-
            [ ! -f /usr/local/bin/sysconfcpus ] 
            && git clone https://github.com/obmarg/libsysconfcpus 
            && cd libsysconfcpus && ./configure && make && sudo make install 
            && cd ..
            && rm -rf libsysconfcpus
      - run:
          # Fix an issue with the purescript pre-compiled binary, which expects to find
          # a library called "libtinfo.so.5" - so we just hack it by symlinking to the newer
          # "libtinfo.so.6" which does exist
          name: Symlink libtinfo.so (pre-compiled purescript needs this)
          command: sudo ln -s /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5
      - run:
          command: which sysconfcpus
      - save_cache:
          key: platform-patches
          paths:
            - /usr/lib/x86_64-linux-gnu/libtinfo.so.5
            - /usr/local/bin/sysconfcpus
      - checkout
      - run:
          command: npm install
      - run:
          command: sysconfcpus -n 2 npm run build
      - run: 
          command: npm run bundle
      - run:
          command: npm run deploy
workflows:
  build:
    jobs:
      - build-and-deploy:
          context:
            - TOM-EC3-AWS
