version: 2.1
orbs:
  node: circleci/node@2.0.2
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - restore_cache:
          keys:
            - purescript-compile-deps-{{ checksum "spago.dhall" }}-{{ checksum "packages.dhall" }}
      - run:
          command: npm run build
      - save_cache:
          key: purescript-compile-deps-{{ checksum "spago.dhall" }}-{{ checksum "packages.dhall" }}
          paths:
            - .spago
            - output
      - run: 
          command: npm run bundle
      - run:
          command: npm run deploy
workflows:
  build:
    jobs:
      - build-and-deploy
