version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  setup-sysconfcpus:
    docker: 
      - image: cimg/node:15.11.0
    steps:
      - run:
          command: git clone https://github.com/obmarg/libsysconfcpus
      - run:
          command: cd libsysconfcpus && ./configure && make && sudo make install 
      - run:
          command: sysconfcpus -n 2 cat /proc/cpuinfo
      - run: 
          command: rm -rf libsysconfcpus
  
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - restore_cache:
          keys:
            - purescript-compile-deps-x{{ checksum "spago.dhall" }}-{{ checksum "packages.dhall" }}
      - run:
          command: sysconfcpus -n 2 npm run build
      - save_cache:
          key: purescript-compile-deps-x{{ checksum "spago.dhall" }}-{{ checksum "packages.dhall" }}
          paths:
            - .spago
            - output
      - run: 
          command: sysconfcpus -n 2 npm run bundle
      - run:
          command: sysconfcpus -n 2 npm run deploy
workflows:
  build:
    jobs:
      - setup-sysconfcpus
      - build-and-deploy
